#!/usr/bin/env bash

cleanup() {
    echo "Cleaning..."
    rm *.class
    rm -rf received_files
}

compile-execute() {
    local file="$1"
    local stripped=${file%.*};
    if [[ ! -f "${stripped}.class"|| $file -nt "${stripped}.class" ]]; then
        echo "Compiling $stripped"
        javac $file
    else
        echo "Already compiled"
    fi

    echo "Executing $stripped"
    java $stripped
}

if [ "$1" == "-c" ]; then
    cleanup
elif [ "$1" == "-r" ]; then
    compile-execute Rendezvous.java
elif [ "$1" == "-p" ]; then
    compile-execute Peer.java
else
    echo "Compiling..."
    javac *.java
fi
